2020-07-23 11:44:37,417 - teradata.udaexec - INFO - Initializing UdaExec...
2020-07-23 11:44:37,418 - teradata.udaexec - INFO - Reading config files: ['C:\\etc\\udaexec.ini: Not Found', 'C:\\Users\\vkadimis\\udaexec.ini: Not Found', 'C:\\Users\\vkadimis\\Desktop\\Vamsi Python Scripts\\My Scripts\\Export Insert Statements\\udaexec.ini: Found']
2020-07-23 11:44:37,418 - teradata.udaexec - INFO - Found run number file: "C:\Users\vkadimis\Desktop\Vamsi Python Scripts\My Scripts\Export Insert Statements\.runNumber"
2020-07-23 11:44:37,419 - teradata.udaexec - INFO - Cleaning up log files older than 90 days.
2020-07-23 11:44:37,419 - teradata.udaexec - INFO - Removed 0 log files.
2020-07-23 11:44:38,632 - teradata.udaexec - INFO - Checkpoint file not found: C:\Users\vkadimis\Desktop\Vamsi Python Scripts\My Scripts\Export Insert Statements\impactAnalysis.checkpoint
2020-07-23 11:44:38,632 - teradata.udaexec - INFO - No previous checkpoint found, executing from beginning...
2020-07-23 11:44:38,633 - teradata.udaexec - INFO - Execution Details:
/********************************************************************************
 * Application Name: impactAnalysis
 *          Version: 2
 *       Run Number: 20200723114437-22
 *             Host: VKADIMIS-4NA7P
 *         Platform: Windows-10-10.0.17134-SP0
 *          OS User: vkadimis
 *   Python Version: 3.7.6
 *  Python Compiler: MSC v.1916 64 bit (AMD64)
 *     Python Build: ('tags/v3.7.6:43364a7ae0', 'Dec 19 2019 00:42:30')
 *  UdaExec Version: 15.10.0.21
 *     Program Name: C:\Users\vkadimis\Desktop\Vamsi Python Scripts\My Scripts\Export Insert Statements\export_insert_statements.py
 *      Working Dir: C:\Users\vkadimis\Desktop\Vamsi Python Scripts\My Scripts\Export Insert Statements
 *          Log Dir: C:\Users\vkadimis\Desktop\Vamsi Python Scripts\My Scripts\Export Insert Statements\logs
 *         Log File: C:\Users\vkadimis\Desktop\Vamsi Python Scripts\My Scripts\Export Insert Statements\logs\impactAnalysis.20200723114437-22.log
 *     Config Files: ['C:\\etc\\udaexec.ini: Not Found', 'C:\\Users\\vkadimis\\udaexec.ini: Not Found', 'C:\\Users\\vkadimis\\Desktop\\Vamsi Python Scripts\\My Scripts\\Export Insert Statements\\udaexec.ini: Found']
 *      Query Bands: ApplicationName=impactAnalysis;Version=2;JobID=20200723114437-22;ClientUser=vkadimis;Production=False;udaAppLogFile=C:\Users\vkadimis\Desktop\Vamsi Python Scripts\My Scripts\Export Insert Statements\logs\impactAnalysis.20200723114437-22.log;UtilityName=PyTd;UtilityVersion=15.10.0.21
********************************************************************************/
2020-07-23 11:44:38,633 - teradata.udaexec - INFO - Creating connection: {'method': 'odbc', 'system': 'TDDEV', 'username': 'vkadimis', 'password': 'XXXXXX', 'driver': 'Teradata', 'authentication': 'LDAP'}
2020-07-23 11:44:38,762 - teradata.tdodbc - INFO - Available drivers: SQL Server, Oracle in OraClient12Home1, BMF SQLite3 ODBC Driver, DataDirect 7.1 DB2 Wire Protocol, DataDirect 7.1 Informix Wire Protocol, DataDirect 7.1 Sybase Wire Protocol, DataDirect 7.1 SQL Server Wire Protocol, DataDirect 7.1 dBaseFile, DataDirect 7.1 FoxPro 3.0, DataDirect 7.1 MySQL Wire Protocol, DataDirect 7.1 New SQL Server Wire Protocol, DataDirect 7.1 Greenplum Wire Protocol, Informatica MongoDB ODBC Driver, DataDirect 7.1 Oracle Wire Protocol, Informatica Data Services ODBC Driver 10.1.0, Informatica Cassandra ODBC Driver, Teradata, Teradata 7.1 DB2 Wire Protocol, Teradata 7.1 Oracle, Teradata 7.1 Oracle Wire Protocol, Teradata 7.1 SQL Server Legacy Wire Protocol, Teradata 7.1 SQL Server Wire Protocol, DataDirect 8.0 New SQL Server Wire Protocol, DataDirect 7.1 PostgreSQL Wire Protocol, DataDirect 8.0 Oracle Wire Protocol, Informatica Data Services ODBC Driver 10.4.0
2020-07-23 11:44:49,714 - teradata.udaexec - INFO - Connection successful. Duration: 11.082 seconds. Details: {'method': 'odbc', 'system': 'TDDEV', 'username': 'vkadimis', 'password': 'XXXXXX', 'driver': 'Teradata', 'authentication': 'LDAP'}
2020-07-23 11:44:49,980 - teradata.udaexec - ERROR - Query Failed! Duration: 0.255 seconds, Query: sel * from STGDB_TS3.WI_DRR_SYSVIEW_PARTY_FDRR sample 100;
Traceback (most recent call last):
  File "C:\Users\vkadimis\AppData\Local\Programs\Python\Python37\lib\site-packages\teradata\udaexec.py", line 790, in _execute
    func(query, params, **kwargs)
  File "C:\Users\vkadimis\AppData\Local\Programs\Python\Python37\lib\site-packages\teradata\tdodbc.py", line 614, in execute
    checkStatus(rc, hStmt=self.hStmt, method="SQLExecDirectW")
  File "C:\Users\vkadimis\AppData\Local\Programs\Python\Python37\lib\site-packages\teradata\tdodbc.py", line 231, in checkStatus
    raise DatabaseError(i[2], u"[{}] {}".format(i[0], msg), i[0])
teradata.api.DatabaseError: (3807, "[42S02] [Teradata][ODBC Teradata Driver][Teradata Database] Object 'STGDB_TS3.WI_DRR_SYSVIEW_PARTY_FDRR' does not exist. ")
2020-07-23 11:44:54,988 - teradata.tdodbc - WARNING - 1 open connections found on exit, attempting to close...
2020-07-23 11:44:55,257 - teradata.udaexec - INFO - UdaExec exiting.
